name: Arduino CI

on: [push, pull_request]

jobs:
  build-sketch:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1.0.0
      - name: Get Python3
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Fetch sketch dependencies
        run: |
          pip3 install pyserial
          arduino-cli core update-index --additional-urls "https://dl.espressif.com/dl/package_esp32_index.json"
          arduino-cli core install esp32:esp32 --additional-urls "https://dl.espressif.com/dl/package_esp32_index.json"
          arduino-cli lib install "Smartcar shield"
          arduino-cli lib install "Wifi"
          arduino-cli lib install "Firebase ESP32 Client"
      - name: Build sketch
        run: arduino-cli compile -b esp32:esp32:esp32doit-devkit-v1 manualCon/manualCon.ino
